#FROM localhost:8082/gitlab/gitlab-ce:15.7.5-ce.0
#FROM localhost:8082/gitlab/gitlab-ce:15.11.11-ce.0
#FROM localhost:8082/gitlab/gitlab-ce:16.0.0-ce.0
#FROM localhost:8082/gitlab/gitlab-ce:16.0.7-ce.0
FROM localhost:8082/gitlab/gitlab-ce:16.1.2-ce.0
