version: '3.5'
services:

  gitlab-server:
    build:
      context: ./gitlab-server/
      dockerfile: dockerfile
    image: gitlab-server
    container_name: gitlab-server
    hostname: gitlab-server
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "8000:80"
      - "8822:22"
    volumes:
      - ./gitlab-data/etc/gitlab:/etc/gitlab
      - ./gitlab-data/var/opt/gitlab:/var/opt/gitlab
      - ./gitlab-data/var/log/gitlab:/var/log/gitlab
    # networks:
    #   - gitlab_net

  gitlab-runner:
    build:
      context: ./gitlab-runner/
      dockerfile: dockerfile
    image: gitlab-runner
    container_name: gitlab-runner
    hostname: gitlab-runner
    tty: true
    stdin_open: true
    # restart: unless-stopped
    # depends_on:
    #   -  gitlab-server
    volumes:
      - ./gitlab-data/etc/gitlab-runner:/etc/gitlab-runner
      - ./gitlab-data/var/run/docker.sock:/var/run/docker.sock
    # networks:
    #   - gitlab_net

# networks:
#   gitlab_net: