FROM localhost:8082/node:18-bullseye-slim
#FROM localhost:8082/ubunut:22.04
#FROM gitlab/gitlab-runner:alpine

RUN apt update && \
	apt install -y mc vim curl wget tmux htop

# Install Gitlab Runner
# https://docs.gitlab.com/runner/install/linux-repository.html
RUN apt install -y git python3
RUN curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash
RUN apt-cache madison gitlab-runner
RUN apt install -y gitlab-runner=15.7.2

